<!DOCTYPE html>
<html>
  <head>
    
    
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      
  Arc &ndash; Test API Site

    </title>
    
    
    <meta name="description" property="og:description" content="Namespace: Rhino.Geometry
Represents the value of a plane, two angles and a radius in a subcurve of a three-dimensional circle.
The curve is parameterized by an angle expressed in radians. For an IsValid arc the total subtended angle AngleRadians() = Domain()(1) - Domain()(0) must satisfy 0 &amp;lt; AngleRadians() &amp;lt; 2*PiThe parameterization of the Arc is inherited from the Circle it is derived from. In particulart -&amp;gt; center &#43; cos(t)radiusxaxis &#43; sin(t)radiusyaxiswhere xaxis and yaxis, (part of Circle.|">
    

    <meta name="apple-mobile-web-app-title" content="Test API Site">
    
    
    
    


    <link rel="stylesheet" href="/hugo/assets/syntax.css">
    <link rel="stylesheet" href="/hugo/assets/primer-build.css">
    <link rel="stylesheet" href="/hugo/assets/style.css">
  </head>


  <body class="bg-gray">
    <div id="holy" class="container-lg bg-white h-100">

      <div id="header" class="px-1 bg-white">
        <nav class="UnderlineNav UnderlineNav--right px-2">
  <a class="UnderlineNav-actions muted-link h2" href="/hugo/">
    Test API Site
  </a>

  
  
</nav>

      </div>

      <div role="main" id="main" class="holy-main markdown-body px-4 bg-white">
        

<div class="Subhead">
  <div class="Subhead-heading">
    <div class="h1 mt-3 mb-1">Arc</div>
  </div>
  <div class="Subhead-description">
    






    
    <div class="float-md-right">
      <span title="Lastmod: 0001-01-01. Published at: 0001-01-01.">
        
          Published: 0001-01-01
        
      </span>
    </div>
    
  </div>
</div>
<article>
  
  <section class="pb-6 mb-3 border-bottom">
    <p><em>Namespace: <a href="../">Rhino.Geometry</a></em></p>
<p>Represents the value of a plane, two angles and a radius in
a subcurve of a three-dimensional circle.</p>
<p>The curve is parameterized by an angle expressed in radians. For an IsValid arc
the total subtended angle AngleRadians() = Domain()(1) - Domain()(0) must satisfy
0 &lt; AngleRadians() &lt; 2*PiThe parameterization of the Arc is inherited from the Circle it is derived from.
In particulart -&gt; center + cos(t)<em>radius</em>xaxis + sin(t)<em>radius</em>yaxiswhere xaxis and yaxis, (part of Circle.Plane) form an othonormal frame of the plane
containing the circle.</p>
<h4 id="static-">static !=</h4>
<ul>
<li>(summary) Determines whether two arcs have different values.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="static--1">static ==</h4>
<ul>
<li>(summary) Determines whether two arcs have equal values.</li>
<li>(since) 5.0</li>
</ul>
<h2 id="constructors">Constructors</h2>
<h4 id="arccircle-circledouble-angleradians">Arc(Circle circle,double angleRadians)</h4>
<ul>
<li>(summary) Initializes a new instance of an arc from a base circle and an angle.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="arccircle-circleinterval-angleintervalradians">Arc(Circle circle,Interval angleIntervalRadians)</h4>
<ul>
<li>(summary) Initializes a new instance of an arc from a base circle and an interval of angles.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="arcplane-planedouble-radiusdouble-angleradians">Arc(Plane plane,double radius,double angleRadians)</h4>
<ul>
<li>(summary) Initializes a new arc from a base plane, a radius value and an angle.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="arcplane-planepoint3d-centerdouble-radiusdouble-angleradians">Arc(Plane plane,Point3d center,double radius,double angleRadians)</h4>
<ul>
<li>(summary) Initializes a new aligned arc at the given center point, with a custom radius and angle.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="arcpoint3d-centerdouble-radiusdouble-angleradians">Arc(Point3d center,double radius,double angleRadians)</h4>
<ul>
<li>(summary) Initializes a new horizontal arc at the given center point, with a custom radius and angle.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="arcpoint3d-startpointpoint3d-pointoninteriorpoint3d-endpoint">Arc(Point3d startPoint,Point3d pointOnInterior,Point3d endPoint)</h4>
<ul>
<li>(summary) Initializes a new arc through three points. If the points are coincident 
or colinear, this will result in an Invalid arc.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="arcpoint3d-pointavector3d-tangentapoint3d-pointb">Arc(Point3d pointA,Vector3d tangentA,Point3d pointB)</h4>
<ul>
<li>(summary) Initializes a new arc from end points and a tangent vector. 
If the tangent is parallel with the endpoints this will result in an Invalid arc.</li>
<li>(since) 5.0</li>
</ul>
<h2 id="properties">Properties</h2>
<h4 id="static-arc-unset">static Arc Unset</h4>
<ul>
<li>(summary) Gets an Arc with Unset components.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="double-angle">double Angle</h4>
<ul>
<li>(summary) Gets or sets the sweep -or subtended- angle (in Radians) for this arc segment.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="double-angledegrees">double AngleDegrees</h4>
<ul>
<li>(summary) Gets or sets the sweep -or subtended- angle (in Radians) for this arc segment.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="interval-angledomain">Interval AngleDomain</h4>
<ul>
<li>(summary) Gets or sets the angle domain (in Radians) of this arc.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="point3d-center">Point3d Center</h4>
<ul>
<li>(summary) Gets or sets the center point for this arc.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="double-circumference">double Circumference</h4>
<ul>
<li>(summary) Gets the circumference of the circle that is coincident with this arc.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="double-diameter">double Diameter</h4>
<ul>
<li>(summary) Gets or sets the Diameter of this arc.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="double-endangle">double EndAngle</h4>
<ul>
<li>(summary) Gets or sets the end angle (in Radians) for this arc segment.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="double-endangledegrees">double EndAngleDegrees</h4>
<ul>
<li>(summary) Gets or sets the end angle (in Radians) for this arc segment.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="point3d-endpoint">Point3d EndPoint</h4>
<ul>
<li>(summary) Gets the end point of the arc.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="bool-iscircle">bool IsCircle</h4>
<ul>
<li>(summary) Gets a value indicating whether or not this arc is a complete circle.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="bool-isvalid">bool IsValid</h4>
<ul>
<li>(summary) Gets a value indicating whether or not this arc is valid.
Detail:
Radius&gt;0 and 0&lt;AngleRadians()&lt;=2*Math.Pi.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="double-length">double Length</h4>
<ul>
<li>(summary) Gets the length of the arc. (Length = Radius * (subtended angle in radians)).</li>
<li>(since) 5.0</li>
</ul>
<h4 id="point3d-midpoint">Point3d MidPoint</h4>
<ul>
<li>(summary) Gets the mid-point of the arc.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="plane-plane">Plane Plane</h4>
<ul>
<li>(summary) Gets or sets the plane in which this arc lies.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="double-radius">double Radius</h4>
<ul>
<li>(summary) Gets or sets the radius of this arc.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="double-startangle">double StartAngle</h4>
<ul>
<li>(summary) Gets or sets the start angle (in Radians) for this arc segment.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="double-startangledegrees">double StartAngleDegrees</h4>
<ul>
<li>(summary) Gets or sets the start angle (in Radians) for this arc segment.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="point3d-startpoint">Point3d StartPoint</h4>
<ul>
<li>(summary) Gets the start point of the arc.</li>
<li>(since) 5.0</li>
</ul>
<h2 id="methods">Methods</h2>
<h4 id="boundingbox-boundingbox">BoundingBox BoundingBox()</h4>
<ul>
<li>(summary) Computes the 3D axis aligned bounding box for this arc.</li>
<li>(since) 5.0</li>
<li>(returns) BoundingBox This is some return comment</li>
</ul>
<h4 id="double-closestparameterpoint3d-testpoint">double ClosestParameter(Point3d testPoint)</h4>
<ul>
<li>(summary) Gets parameter on the arc closest to a test point.</li>
<li>(since) 5.0</li>
<li>(returns) double This is some return comment</li>
</ul>
<h4 id="point3d-closestpointpoint3d-testpoint">Point3d ClosestPoint(Point3d testPoint)</h4>
<ul>
<li>(summary) Computes the point on an arc that is closest to a test point.</li>
<li>(since) 5.0</li>
<li>(returns) Point3d This is some return comment</li>
</ul>
<h4 id="bool-epsilonequalsarc-otherdouble-epsilon">bool EpsilonEquals(Arc other,double epsilon)</h4>
<ul>
<li>(summary) Check that all values in other are within epsilon of the values in this</li>
<li>(since) 5.4</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-equalsarc-other">bool Equals(Arc other)</h4>
<ul>
<li>(summary) Determines whether another arc has the same value as this arc.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-equalsobject-obj">bool Equals(object obj)</h4>
<ul>
<li>(summary) Determines whether another object is an arc and has the same value as this arc.</li>
<li>(since) (unknown)</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="int-gethashcode">int GetHashCode()</h4>
<ul>
<li>(summary) Computes a hash code for the present arc.</li>
<li>(since) (unknown)</li>
<li>(returns) int This is some return comment</li>
</ul>
<h4 id="point3d-pointatdouble-t">Point3d PointAt(double t)</h4>
<ul>
<li>(summary) Gets the point at the given arc parameter.</li>
<li>(since) 5.0</li>
<li>(returns) Point3d This is some return comment</li>
</ul>
<h4 id="void-reverse">void Reverse()</h4>
<ul>
<li>(summary) Reverses the orientation of the arc. Changes the domain from [a,b]
to [-b,-a].</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="vector3d-tangentatdouble-t">Vector3d TangentAt(double t)</h4>
<ul>
<li>(summary) Gets the tangent at the given parameter.</li>
<li>(since) 5.0</li>
<li>(returns) Vector3d This is some return comment</li>
</ul>
<h4 id="nurbscurve-tonurbscurve">NurbsCurve ToNurbsCurve()</h4>
<ul>
<li>(summary) Initializes a nurbs curve representation of this arc. 
This amounts to the same as calling NurbsCurve.CreateFromArc().</li>
<li>(since) 5.0</li>
<li>(returns) NurbsCurve This is some return comment</li>
</ul>
<h4 id="nurbscurve-tonurbscurveint-degreeint-cvcount">NurbsCurve ToNurbsCurve(int degree,int cvCount)</h4>
<ul>
<li>(summary) Create a uniform non-ratonal cubic NURBS approximation of an arc.</li>
<li>(since) 6.0</li>
<li>(returns) NurbsCurve This is some return comment</li>
</ul>
<h4 id="bool-transformtransform-xform">bool Transform(Transform xform)</h4>
<ul>
<li>(summary) Transforms the arc using a Transformation matrix.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-triminterval-domain">bool Trim(Interval domain)</h4>
<ul>
<li>(summary) Sets arc&rsquo;s angle domain (in radians) as a subdomain of the circle.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>

  </section>

  <section>
    
      
    
  </section>
</article>

      </div>

      <div id="side" class="pr-1 bg-white">
        <aside class="pr-3">
          
  
    <div id="toc" class="Box Box--blue mb-3">
      <b>Arc</b><nav id="TableOfContents">
  <ul>
    <li>
      <ul>
        <li></li>
      </ul>
    </li>
    <li><a href="#constructors">Constructors</a>
      <ul>
        <li></li>
      </ul>
    </li>
    <li><a href="#properties">Properties</a>
      <ul>
        <li></li>
      </ul>
    </li>
    <li><a href="#methods">Methods</a>
      <ul>
        <li></li>
      </ul>
    </li>
  </ul>
</nav></div>
  

  
    <div>
      
    </div>
  

        </aside>
      </div>

      <div id="footer" class="pt-2 pb-3 bg-white text-center">
        

  <span class="text-small text-gray">
    

    Powered by the
    <a href="https://github.com/qqhann/hugo-primer" class="link-gray-dark">Hugo-Primer</a> theme for
    <a href="https://gohugo.io" class="link-gray-dark">Hugo</a>.
  </span>


      </div>
    </div>

    
    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    
    <script type="text/x-mathjax-config">MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] } });</script>
    
  </body>
</html>
