<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Rhino.Input.Custom on Test API Site</title>
    <link>/apidocs/hugo/posts/rhino/input/custom/</link>
    <description>Recent content in Rhino.Input.Custom on Test API Site</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    
	<atom:link href="/apidocs/hugo/posts/rhino/input/custom/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>CommandLineOption</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/commandlineoption/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/commandlineoption/</guid>
      <description>Namespace: Rhino.Input.Custom
public class CommandLineOptionProperties int CurrentListOptionIndex  (summary) (since) 5.0  string EnglishName  (summary) The English command option name (since) 5.0  int Index  (summary) (since) 5.0  string LocalName  (summary) The localized command option name (since) 6.24  string StringOptionValue  (summary) Assigned by RhinoGet.Get if an option value is specified in a script or by a command window control. (since) 6.24  Methods static bool IsValidOptionName(string optionName)  (summary) Test a string to see if it can be used as an option name in any of the RhinoGet::AddCommandOption&amp;hellip;() functions.</description>
    </item>
    
    <item>
      <title>GetArc</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getarc/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getarc/</guid>
      <description>Namespace: Rhino.Input.Custom
public class GetArcConstructors GetArc()  (summary) (since) 6.0  Properties bool AllowDeformable  (summary) Allow for deformable options (since) 6.0  double DefaultRadius  (summary) Default radius used for start and end radius (since) 6.0  bool Deformable  (summary) Is the deformable option set (since) 6.0  int DeformableDegree  (summary) (since) 6.0  int DeformablePointCount  (summary) (since) 6.0  Methods void Dispose()  (summary) Actively reclaims unmanaged resources that this instance uses.</description>
    </item>
    
    <item>
      <title>GetBaseClass</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getbaseclass/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getbaseclass/</guid>
      <description>Namespace: Rhino.Input.Custom
Base class for GetObject, GetPoint, GetSphere, etc.
You will never directly create a GetBaseClass but you will use its member functions after calling GetObject.Gets(), GetPoint.Get(), and so on.
Provides tools to set command prompt, set command options, and specify if the &amp;ldquo;get&amp;rdquo; can optionally accept numbers, nothing (pressing enter), and undo.
public class GetBaseClassMethods static void PostCustomMessage(object messageData)  (summary) (since) 5.0 (returns) void This is some return comment  void AcceptColor(bool enable)  (summary) If you want to allow the user to be able to type in a color r,g,b or name during GetPoint.</description>
    </item>
    
    <item>
      <title>GetCancel</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getcancel/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getcancel/</guid>
      <description>Namespace: Rhino.Input.Custom
public class GetCancelTaskCompleted  (summary) (since) 6.0  Constructors GetCancel()  (summary) (since) 6.0  Properties IProgressProgress  (summary) (since) 6.0  string ProgressMessage  (summary) (since) 6.0  bool ProgressReporting  (summary) (since) 6.0  CancellationToken Token  (summary) (since) 6.0  Methods Result Wait(Task task,RhinoDoc doc)  (summary) Awaits a particular task to finish. (since) 7.0 (returns) Result This is some return comment  Result Wait(Tasktask,RhinoDoc doc)  (summary) Awaits a particular task to finish.</description>
    </item>
    
    <item>
      <title>GetCircle</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getcircle/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getcircle/</guid>
      <description>Namespace: Rhino.Input.Custom
public class GetCircleConstructors GetCircle()  (summary) (since) 6.0  Properties bool AllowDeformable  (summary) Allow for deformable options (since) 6.0  double DefaultSize  (summary) Default radius or diameter (based on InDiameterMode) (since) 6.0  bool Deformable  (summary) Is the deformable option set (since) 6.0  int DeformableDegree  (summary) (since) 6.0  int DeformablePointCount  (summary) (since) 6.0  bool InDiameterMode  (summary) Determines if the &amp;ldquo;size&amp;rdquo; value is reperesenting a radius or diameter (since) 6.</description>
    </item>
    
    <item>
      <title>GetCone</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getcone/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getcone/</guid>
      <description>Namespace: Rhino.Input.Custom
Class provides user interface to define a cone.
public class GetConeConstructors GetCone()  (summary) (since) 6.0  Properties bool AllowInputAngle  (summary) (since) 6.0  double ApexAngleDegrees  (summary) (since) 6.0  double BaseAngleDegrees  (summary) (since) 6.0  bool Cap  (summary) Gets or sets whether or not the output should be capped. (since) 6.0  ConeConstraint ConeConstraint  (summary) State of the cone/cyl constraint option. When the cone/cyl option is selected, the circle is being made as a base for a cone/cyl.</description>
    </item>
    
    <item>
      <title>GetCylinder</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getcylinder/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getcylinder/</guid>
      <description>Namespace: Rhino.Input.Custom
Class provides user interface to define a cylinder.
public class GetCylinderConstructors GetCylinder()  (summary) (since) 6.0  Properties bool BothSidesOption  (summary) Determine if the &amp;ldquo;both sides&amp;rdquo; option is enabled (since) 6.0  bool Cap  (summary) Gets or sets whether or not the output should be capped. (since) 6.0  CylinderConstraint CylinderConstraint  (summary) State of the cone/cyl constraint option. When the cone/cyl option is selected, the circle is being made as a base for a cone/cyl.</description>
    </item>
    
    <item>
      <title>GetEllipsoid</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getellipsoid/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getellipsoid/</guid>
      <description>Namespace: Rhino.Input.Custom
Class provides user interface to define a truncated cone.
public class GetEllipsoidConstructors GetEllipsoid()  (summary) (since) 7.0  Properties Geometry.Point3d FirstPoint  (summary) Returns the first point. If in &amp;ldquo;from foci&amp;rdquo; mode, then this is the first foci point. (since) 7.0  bool IsModeFromFoci  (summary) Indicates the ellipsoid was created from foci. (since) 7.0  bool MarkFoci  (summary) Indicates the user wants the ellipsoid foci marked with point objects.</description>
    </item>
    
    <item>
      <title>GetInteger</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getinteger/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getinteger/</guid>
      <description>Namespace: Rhino.Input.Custom
Used to get integer numbers.
public class GetIntegerConstructors GetInteger()  (summary) (since) 5.0  Methods GetResult Get()  (summary) Call to get an integer. (since) 5.0 (returns) GetResult This is some return comment  int Number()  (summary) (since) 5.0 (returns) int This is some return comment  void SetLowerLimit(int lowerLimit,bool strictlyGreaterThan)  (summary) Sets a lower limit on the number that can be returned. By default there is no lower limit.</description>
    </item>
    
    <item>
      <title>GetLine</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getline/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getline/</guid>
      <description>Namespace: Rhino.Input.Custom
Use to interactively get a line. The Rhino &amp;ldquo;Line&amp;rdquo; command uses GetLine.
public class GetLineConstructors GetLine()  (summary) (since) 5.1  Properties bool AcceptZeroLengthLine  (summary) Controls whether or not a zero length line is acceptable. The default is to require the user to keep picking the end point until we get a point different than the start point. (since) 5.1  System.Drawing.Color FeedbackColor  (summary) If set, the feedback color is used to draw the dynamic line when the second point is begin picked.</description>
    </item>
    
    <item>
      <title>GetNumber</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getnumber/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getnumber/</guid>
      <description>Namespace: Rhino.Input.Custom
Used to get double precision numbers.
public class GetNumberConstructors GetNumber()  (summary) Create a new GetNumber. (since) 5.0  Methods GetResult Get()  (summary) Call to get a number. (since) 5.0 (returns) GetResult This is some return comment  void SetLowerLimit(double lowerLimit,bool strictlyGreaterThan)  (summary) Sets a lower limit on the number that can be returned. By default there is no lower limit. (since) 5.0 (returns) void This is some return comment  void SetUpperLimit(double upperLimit,bool strictlyLessThan)  (summary) Sets an upper limit on the number that can be returned.</description>
    </item>
    
    <item>
      <title>GetObject</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getobject/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getobject/</guid>
      <description>Namespace: Rhino.Input.Custom
The GetObject class is the tool commands use to interactively select objects.
public class GetObjectConstructors GetObject()  (summary) (since) 5.0  Properties bool AlreadySelectedObjectSelect  (summary) Allow selecting objects that are already selected. By default, GetObjects() disallows selection of objects that are already selected to avoid putting the same object in the selection set more than once. Calling EnableAlreadySelectedObjectSelect = true overrides that restriction and allows selected objects to be selected and returned by GetObjects.</description>
    </item>
    
    <item>
      <title>GetOption</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getoption/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getoption/</guid>
      <description>Namespace: Rhino.Input.Custom
If you want to explicitly get string input, then use GetString class with options. If you only want to get options, then use this class (GetOption)
public class GetOptionConstructors GetOption()  (summary) (since) 5.0  Methods GetResult Get()  (summary) Call to get an option. A return value of &amp;ldquo;option&amp;rdquo; means the user selected a valid option. Use Option() the determine which option. (since) 5.0 (returns) GetResult This is some return comment  </description>
    </item>
    
    <item>
      <title>GetPoint</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getpoint/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getpoint/</guid>
      <description>Namespace: Rhino.Input.Custom
Used to interactively get a point.
public class GetPointDynamicDraw   (summary) Event to use if you want to dynamically draw things as the mouse/digitizer moves. Every time the mouse moves, DynamicDraw will be called once per viewport. The calls to DynamicDraw happen AFTER the call to MouseMove.
If you are drawing anything that takes a long time, periodically call InterruptMouseMove() to see if you should stop.</description>
    </item>
    
    <item>
      <title>GetPointDrawEventArgs</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getpointdraweventargs/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getpointdraweventargs/</guid>
      <description>Namespace: Rhino.Input.Custom
Arguments for drawing during point getting.
public class GetPointDrawEventArgsProperties Point3d CurrentPoint  (summary) (since) 5.0  GetPoint Source  (summary) GetPoint class that this draw event originated from. (since) 5.0  </description>
    </item>
    
    <item>
      <title>GetPointMouseEventArgs</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getpointmouseeventargs/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getpointmouseeventargs/</guid>
      <description>Namespace: Rhino.Input.Custom
Arguments for mouse information during point getting.
public class GetPointMouseEventArgsProperties bool ControlKeyDown  (summary) (since) 5.0  bool LeftButtonDown  (summary) (since) 5.0  bool MiddleButtonDown  (summary) (since) 5.0  Point3d Point  (summary) (since) 5.0  bool RightButtonDown  (summary) (since) 5.0  bool ShiftKeyDown  (summary) (since) 5.0  GetPoint Source  (summary) (since) 5.0  RhinoViewport Viewport  (summary) (since) 5.0  System.Drawing.Point WindowPoint  (summary) (since) 5.</description>
    </item>
    
    <item>
      <title>GetPolyline</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getpolyline/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getpolyline/</guid>
      <description>Namespace: Rhino.Input.Custom
Use to interactively get a polyline.
public class GetPolylineConstructors GetPolyline()  (summary) (since) 6.0  Properties string FirstPointPrompt  (summary) Prompt when getting first point (since) 6.0  string FourthPointPrompt  (summary) Prompt when getting fourth point (since) 6.0  int MaxPointCount  (summary) (since) 6.0  int MinPointCount  (summary) (since) 6.0  string SecondPointPrompt  (summary) Prompt when getting second point (since) 6.0  string ThirdPointPrompt  (summary) Prompt when getting third point (since) 6.</description>
    </item>
    
    <item>
      <title>GetSphere</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getsphere/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getsphere/</guid>
      <description>Namespace: Rhino.Input.Custom
Class provides user interface to define a sphere.
public class GetSphereConstructors GetSphere()  (summary) (since) 7.0  Properties double DefaultSize  (summary) Default radius or diameter (based on InDiameterMode) (since) 7.0  bool InDiameterMode  (summary) Determines if the &amp;ldquo;size&amp;rdquo; value is reperesenting a radius or diameter (since) 7.0  Methods void Dispose()  (summary) Actively reclaims unmanaged resources that this instance uses. (since) 7.0 (returns) void This is some return comment  Commands.</description>
    </item>
    
    <item>
      <title>GetString</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/getstring/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/getstring/</guid>
      <description>Namespace: Rhino.Input.Custom
Used to get strings.
public class GetStringConstructors GetString()  (summary) Constructs a new GetString. (since) 5.0  Methods GetResult Get()  (summary) Returns the string that the user typed. By default, space stops the string input. (since) 5.0 (returns) GetResult This is some return comment  GetResult GetLiteralString()  (summary) Returns the string that the user typed. By default, space does not stop input. (since) 5.0 (returns) GetResult This is some return comment  </description>
    </item>
    
    <item>
      <title>GetTorus</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/gettorus/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/gettorus/</guid>
      <description>Namespace: Rhino.Input.Custom
Class provides user interface to define a torus.
public class GetTorusConstructors GetTorus()  (summary) (since) 7.0  Properties double DefaultSize  (summary) Default radius or diameter (based on InDiameterMode) (since) 7.0  bool FixInnerRadius  (summary) Second radius opion. The first radius chosen sets the inner dimension of the torus and the second radius is constrained to be outside of the first radius. (since) 7.0  bool InDiameterMode  (summary) Determines if the &amp;ldquo;size&amp;rdquo; value is reperesenting a radius or diameter (since) 7.</description>
    </item>
    
    <item>
      <title>GetTransform</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/gettransform/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/gettransform/</guid>
      <description>Namespace: Rhino.Input.Custom
Used for getting a Transform
public class GetTransformProperties bool HaveTransform  (summary) (since) 5.0  Collections.TransformObjectList ObjectList  (summary) (since) 5.0  Transform Transform  (summary) (since) 5.0  Methods void AddTransformObjects(TransformObjectList list)  (summary) Adds any objects you want transformed and grips you want transformed. Make sure no duplicates are in the list and that no grip ownwers are passed in as objects. (since) 5.0 (returns) void This is some return comment  Transform CalculateTransform(RhinoViewport viewport,Point3d point)  (summary) Retrieves the final transformation.</description>
    </item>
    
    <item>
      <title>GetTruncatedCone</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/gettruncatedcone/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/gettruncatedcone/</guid>
      <description>Namespace: Rhino.Input.Custom
Class provides user interface to define a truncated cone.
public class GetTruncatedConeConstructors GetTruncatedCone()  (summary) (since) 7.0  Properties bool Cap  (summary) Gets or sets whether or not the output should be capped. (since) 7.0  CylinderConstraint CylinderConstraint  (summary) State of the cone/cyl constraint option. When the cone/cyl option is selected, the circle is being made as a base for a cone/cyl. By default the vertical cone/cyl option not available but is not selected.</description>
    </item>
    
    <item>
      <title>OptionColor</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/optioncolor/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/optioncolor/</guid>
      <description>Namespace: Rhino.Input.Custom
public class OptionColorConstructors OptionColor(Color initialValue)  (summary) (since) 5.0  Properties Color CurrentValue  (summary) (since) 5.0  Color InitialValue  (summary) (since) 5.0  Methods void Dispose()  (summary) (since) 5.0 (returns) void This is some return comment  </description>
    </item>
    
    <item>
      <title>OptionDouble</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/optiondouble/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/optiondouble/</guid>
      <description>Namespace: Rhino.Input.Custom
public class OptionDoubleConstructors OptionDouble(double initialValue)  (summary) (since) 5.0  OptionDouble(double initialValue,bool setLowerLimit,double limit)  (summary) Initializes a new instance of the double option class. (since) 5.0  OptionDouble(double initialValue,double lowerLimit,double upperLimit)  (summary) Initializes a new instance of the class with lower and upper limits. (since) 5.0  Properties double CurrentValue  (summary) (since) 5.0  double InitialValue  (summary) (since) 5.0  Methods void Dispose()  (summary) (since) 5.</description>
    </item>
    
    <item>
      <title>OptionInteger</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/optioninteger/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/optioninteger/</guid>
      <description>Namespace: Rhino.Input.Custom
public class OptionIntegerConstructors OptionInteger(int initialValue)  (summary) (since) 5.0  OptionInteger(int initialValue,bool setLowerLimit,int limit)  (summary) Initializes a new instance of the class. (since) 5.0  OptionInteger(int initialValue,int lowerLimit,int upperLimit)  (summary) Initializes a new instance of the class wiht both lower and upper limits. (since) 5.0  Properties int CurrentValue  (summary) (since) 5.0  int InitialValue  (summary) (since) 5.0  Methods void Dispose()  (summary) (since) 5.</description>
    </item>
    
    <item>
      <title>OptionToggle</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/optiontoggle/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/optiontoggle/</guid>
      <description>Namespace: Rhino.Input.Custom
public class OptionToggleConstructors OptionToggle(bool initialValue,LocalizeStringPair offValue,LocalizeStringPair onValue)  (summary) (since) 5.0  OptionToggle(bool initialValue,string offValue,string onValue)  (summary) (since) 5.0  Properties bool CurrentValue  (summary) (since) 5.0  bool InitialValue  (summary) (since) 5.0  Methods void Dispose()  (summary) (since) 5.0 (returns) void This is some return comment  </description>
    </item>
    
    <item>
      <title>PickContext</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/pickcontext/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/pickcontext/</guid>
      <description>Namespace: Rhino.Input.Custom
Utility for determining if objects are picked
public class PickContextConstructors PickContext()  (summary) (since) 5.0  Properties GetObject GetObjectUsed  (summary) (since) 5.0  bool PickGroupsEnabled  (summary) Thue if GroupObjects should be added to the pick list (since) 5.0  Geometry.Line PickLine  (summary) pick chord starts on near clipping plane and ends on far clipping plane. (since) 5.0  PickMode PickMode  (summary) (since) 5.0  PickStyle PickStyle  (summary) (since) 5.</description>
    </item>
    
    <item>
      <title>TaskCompleteEventArgs</title>
      <link>/apidocs/hugo/posts/rhino/input/custom/taskcompleteeventargs/</link>
      <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
      
      <guid>/apidocs/hugo/posts/rhino/input/custom/taskcompleteeventargs/</guid>
      <description>Namespace: Rhino.Input.Custom
public class TaskCompleteEventArgsConstructors TaskCompleteEventArgs(Task task,RhinoDoc doc)  (summary) (since) 6.0  Properties RhinoDoc Doc  (summary) (since) 6.0  bool Redraw  (summary) (since) 6.0  Task Task  (summary) (since) 6.0  </description>
    </item>
    
  </channel>
</rss>