---
title: "Rhino.DocObjects.ClippingPlaneObject"
date: 2020-03-10 09:24:55Z
draft: false
---

# Properties
## Rhino.Geometry.ClippingPlaneSurface ClippingPlaneGeometry
- (summary) 
     Gets the clipping plane surface.
     
- (since) 5.0
# Methods
## bool AddClipViewport(RhinoViewport viewport,bool commit)
- (summary) 
     Adds a viewport to the list of viewports that this clipping plane clips.
     
- (since) 6.1
- (returns) bool This is some return comment
## bool RemoveClipViewport(RhinoViewport viewport,bool commit)
- (summary) 
     Removes a viewport from the list of viewports that this clipping plane clips.
     
- (since) 6.1
- (returns) bool This is some return comment
