<!DOCTYPE html>
<html>
  <head>
    
    
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      
  GetObject &ndash; Test API Site

    </title>
    
    
    <meta name="description" property="og:description" content="Namespace: Rhino.Input.Custom
The GetObject class is the tool commands use to interactively select objects.
public class GetObjectConstructors GetObject()  (summary) (since) 5.0  Properties bool AlreadySelectedObjectSelect  (summary) Allow selecting objects that are already selected. By default, GetObjects() disallows selection of objects that are already selected to avoid putting the same object in the selection set more than once. Calling EnableAlreadySelectedObjectSelect = true overrides that restriction and allows selected objects to be selected and returned by GetObjects.|">
    

    <meta name="apple-mobile-web-app-title" content="Test API Site">
    
    
    
    


    <link rel="stylesheet" href="/hugo/assets/syntax.css">
    <link rel="stylesheet" href="/hugo/assets/primer-build.css">
    <link rel="stylesheet" href="/hugo/assets/style.css">
  </head>


  <body class="bg-gray">
    <div id="holy" class="container-lg bg-white h-100">

      <div id="header" class="px-1 bg-white">
        <nav class="UnderlineNav UnderlineNav--right px-2">
  <a class="UnderlineNav-actions muted-link h2" href="/hugo/">
    Test API Site
  </a>

  
  
</nav>

      </div>

      <div role="main" id="main" class="holy-main markdown-body px-4 bg-white">
        

<div class="Subhead">
  <div class="Subhead-heading">
    <div class="h1 mt-3 mb-1">GetObject</div>
  </div>
  <div class="Subhead-description">
    






    
    <div class="float-md-right">
      <span title="Lastmod: 0001-01-01. Published at: 0001-01-01.">
        
          Published: 0001-01-01
        
      </span>
    </div>
    
  </div>
</div>
<article>
  
  <section class="pb-6 mb-3 border-bottom">
    <p><em>Namespace: <a href="../">Rhino.Input.Custom</a></em></p>
<p>The GetObject class is the tool commands use to interactively select objects.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-cs" data-lang="cs"><span style="color:#66d9ef">public</span> <span style="color:#66d9ef">class</span> <span style="color:#a6e22e">GetObject</span>
</code></pre></div><h2 id="constructors">Constructors</h2>
<h4 id="getobject">GetObject()</h4>
<ul>
<li>(summary)</li>
<li>(since) 5.0</li>
</ul>
<h2 id="properties">Properties</h2>
<h4 id="bool-alreadyselectedobjectselect">bool AlreadySelectedObjectSelect</h4>
<ul>
<li>(summary) Allow selecting objects that are already selected. By default, GetObjects() disallows
selection of objects that are already selected to avoid putting the same object
in the selection set more than once. Calling EnableAlreadySelectedObjectSelect = true
overrides that restriction and allows selected objects to be selected and
returned by GetObjects. This is useful because, coupled with the return immediately
mode of GetObjects(1, -1), it is possible to select a selected object to deselect
when the selected objects are being managed outside GetObjects() as in the case of
CRhinoPolyEdge::GetEdge().</li>
<li>(since) 5.0</li>
</ul>
<h4 id="bool-bottomobjectpreference">bool BottomObjectPreference</h4>
<ul>
<li>(summary) By default, if a call to Input is permitted to select different parts of
the same object, like a polysurface, a surface and an edge, then the
top-most object is prefered. (polysurface beats face beats edge). If
you want the bottom most object to be prefered, then call 
EnableBottomObjectPreference = True before calling GetObjects().</li>
<li>(since) 5.0</li>
</ul>
<h4 id="bool-chooseonequestion">bool ChooseOneQuestion</h4>
<ul>
<li>(summary) By default, if a call to Input is permitted to select different parts
of the same object, like a polysurface and an edge of that polysurface,
then the top-most object is automatically selected. If you want the
choose-one-object mechanism to include pop up in these cases, then call
EnableChooseOneQuestion = True before calling GetObjects().</li>
<li>(since) 5.0</li>
</ul>
<h4 id="bool-deselectallbeforepostselect">bool DeselectAllBeforePostSelect</h4>
<ul>
<li>(summary) True if pre-selected input will be deselected before
post-selection begins when no pre-selected input is valid.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="geometryattributefilter-geometryattributefilter">GeometryAttributeFilter GeometryAttributeFilter</h4>
<ul>
<li>(summary) The geometry attribute filter provides a secondary filter that
can be used to restrict which objects can be selected. Control
of the type of geometry (points, curves, surfaces, meshes, etc.)
is provided by GetObject.SetGeometryFilter. The geometry attribute
filter is used to require the selected geometry to have certain
attributes (open, closed, etc.). The default attribute filter
permits selection of all types of geometry.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="objecttype-geometryfilter">ObjectType GeometryFilter</h4>
<ul>
<li>(summary) The geometry type filter controls which types of geometry
(points, curves, surfaces, meshes, etc.) can be selected.
The default geometry type filter permits selection of all
types of geometry.
NOTE: the filter can be a bitwise combination of multiple ObjectTypes.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="bool-groupselect">bool GroupSelect</h4>
<ul>
<li>(summary) By default, groups are ignored in GetObject. If you want your call to
GetObjects() to select every object in a group that has any objects
selected, then enable group selection.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="bool-inactivedetailpickenabled">bool InactiveDetailPickEnabled</h4>
<ul>
<li>(summary) By default, objects in inactive details are not permitted to be picked.
In a few rare cases this is used (ex. picking circles during DimRadius)</li>
<li>(since) 5.8</li>
</ul>
<h4 id="int-objectcount">int ObjectCount</h4>
<ul>
<li>(summary) Gets the number of objects that were selected.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="bool-objectswerepreselected">bool ObjectsWerePreselected</h4>
<ul>
<li>(summary)</li>
<li>(since) 5.0</li>
</ul>
<h4 id="bool-onebyonepostselect">bool OneByOnePostSelect</h4>
<ul>
<li>(summary) In one-by-one post selection, the user is forced
to select objects by post picking them one at a time.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="bool-referenceobjectselect">bool ReferenceObjectSelect</h4>
<ul>
<li>(summary) By default, reference objects can be selected. If you do not want to be
able to select reference objects, then call EnableReferenceObjectSelect=false.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="uint-serialnumber">uint SerialNumber</h4>
<ul>
<li>(summary) Each instance of GetObject has a unique runtime serial number that
is used to identify object selection events associated with that instance.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="bool-subobjectselect">bool SubObjectSelect</h4>
<ul>
<li>(summary) By default, GetObject.Input will permit a user to select
sub-objects (like a curve in a b-rep or a curve in a group).
If you only want the user to select &ldquo;top&rdquo; level objects,
then call EnableSubObjectSelect = false.</li>
<li>(since) 5.0</li>
</ul>
<h2 id="methods">Methods</h2>
<h4 id="static-getobject-activegetobjectrhinodoc-doc">static GetObject ActiveGetObject(RhinoDoc doc)</h4>
<ul>
<li>(summary) Get the currently running GetObject for a given document</li>
<li>(since) 6.3</li>
<li>(returns) GetObject This is some return comment</li>
</ul>
<h4 id="void-appendtopicklistobjref-objref">void AppendToPickList(ObjRef objref)</h4>
<ul>
<li>(summary)</li>
<li>(since) 6.3</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="void-clearobjects">void ClearObjects()</h4>
<ul>
<li>(summary) Clear possible special object drawing</li>
<li>(since) 6.12</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="bool-customgeometryfilterrhinoobject-rhobjectgeometrybase-geometrycomponentindex-componentindex">bool CustomGeometryFilter(RhinoObject rhObject,GeometryBase geometry,ComponentIndex componentIndex)</h4>
<ul>
<li>(summary) Checks geometry to see if it can be selected.
Override to provide fancy filtering.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="void-disablepreselect">void DisablePreSelect()</h4>
<ul>
<li>(summary)</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="void-enableclearobjectsonentrybool-enable">void EnableClearObjectsOnEntry(bool enable)</h4>
<ul>
<li>(summary) By default the picked object list is cleared when GetObject.GetObjects() is called.
If you are reusing a GetObject class and do not want the existing object list
cleared when you call Input, then call EnableClearObjectsOnEntry(false) before
calling GetObjects().</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="void-enablehighlightbool-enable">void EnableHighlight(bool enable)</h4>
<ul>
<li>(summary) By default, any object post-pick selected by GetObjects() is highlighted.
If you want to post-pick objects and not have them automatically highlight,
then call EnableHighlight = false.</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="void-enableignoregripsbool-enable">void EnableIgnoreGrips(bool enable)</h4>
<ul>
<li>(summary) By default, post selection will select objects with grips on. If you do
not want to be able to post select objects with grips on, then call
EnableIgnoreGrips = false. The ability to preselect an object with grips
on is determined by the value returned by the virtual
RhinoObject.IsSelectableWithGripsOn.</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="void-enablepostselectbool-enable">void EnablePostSelect(bool enable)</h4>
<ul>
<li>(summary) Control the availability of post selection in GetObjects.</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="void-enablepreselectbool-enablebool-ignoreunacceptablepreselectedobjects">void EnablePreSelect(bool enable,bool ignoreUnacceptablePreselectedObjects)</h4>
<ul>
<li>(summary) Control the pre selection behavior GetObjects.</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="void-enablepressenterwhendonepromptbool-enable">void EnablePressEnterWhenDonePrompt(bool enable)</h4>
<ul>
<li>(summary) By default, when GetObject.GetObjects is called with minimumNumber &gt; 0
and maximumNumber = 0, the command prompt automatically includes &ldquo;Press Enter
when done&rdquo; after the user has selected at least minimumNumber of objects. If
you want to prohibit the addition of the &ldquo;Press Enter when done&rdquo;, then call
EnablePressEnterWhenDonePrompt = false;</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="void-enableselpreviousbool-enable">void EnableSelPrevious(bool enable)</h4>
<ul>
<li>(summary) By default, any object selected during a command becomes part of the
&ldquo;previous selection set&rdquo; and can be reselected by the SelPrev command.
If you need to select objects but do not want them to be selected by
a subsquent call to SelPrev, then call EnableSelPrev = false.</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="void-enableunselectobjectsonexitbool-enable">void EnableUnselectObjectsOnExit(bool enable)</h4>
<ul>
<li>(summary) By default any objects in the object list are unselected when GetObject.GetObjects()
exits with any return code besides Object. If you want to leave the objects
selected when non-object input is returned, then call EnableUnselectObjectsOnExit(false)
before calling GetObjects().</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="getresult-get">GetResult Get()</h4>
<ul>
<li>(summary) Call to select a single object.</li>
<li>(since) 5.0</li>
<li>(returns) GetResult This is some return comment</li>
</ul>
<h4 id="getresult-getmultipleint-minimumnumberint-maximumnumber">GetResult GetMultiple(int minimumNumber,int maximumNumber)</h4>
<ul>
<li>(summary) Call to select objects.</li>
<li>(since) 5.0</li>
<li>(returns) GetResult This is some return comment</li>
</ul>
<h4 id="objref-objectint-index">ObjRef Object(int index)</h4>
<ul>
<li>(summary)</li>
<li>(since) 5.0</li>
<li>(returns) ObjRef This is some return comment</li>
</ul>
<h4 id="objref-objects">ObjRef[] Objects()</h4>
<ul>
<li>(summary)</li>
<li>(since) 5.0</li>
<li>(returns) ObjRef[] This is some return comment</li>
</ul>
<h4 id="bool-passesgeometryattributefilterrhinoobject-rhobjectgeometrybase-geometrycomponentindex-componentindex">bool PassesGeometryAttributeFilter(RhinoObject rhObject,GeometryBase geometry,ComponentIndex componentIndex)</h4>
<ul>
<li>(summary) Checks geometry to see if it passes the basic GeometryAttributeFilter.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="void-setcustomgeometryfiltergetobjectgeometryfilter-filter">void SetCustomGeometryFilter(GetObjectGeometryFilter filter)</h4>
<ul>
<li>(summary) Set filter callback function that will be called by the CustomGeometryFilter</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="void-setpressenterwhendonepromptstring-prompt">void SetPressEnterWhenDonePrompt(string prompt)</h4>
<ul>
<li>(summary) The default prompt when EnablePressEnterWhenDonePrompt is enabled is &ldquo;Press Enter
when done&rdquo;. Use this function to specify a different string to be appended.</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>

  </section>

  <section>
    
      
    
  </section>
</article>

      </div>

      <div id="side" class="pr-1 bg-white">
        <aside class="pr-3">
          
  
    <div id="toc" class="Box Box--blue mb-3">
      <b>GetObject</b><nav id="TableOfContents">
  <ul>
    <li><a href="#constructors">Constructors</a>
      <ul>
        <li></li>
      </ul>
    </li>
    <li><a href="#properties">Properties</a>
      <ul>
        <li></li>
      </ul>
    </li>
    <li><a href="#methods">Methods</a>
      <ul>
        <li></li>
      </ul>
    </li>
  </ul>
</nav></div>
  

  
    <div>
      
    </div>
  

        </aside>
      </div>

      <div id="footer" class="pt-2 pb-3 bg-white text-center">
        

  <span class="text-small text-gray">
    

    Powered by the
    <a href="https://github.com/qqhann/hugo-primer" class="link-gray-dark">Hugo-Primer</a> theme for
    <a href="https://gohugo.io" class="link-gray-dark">Hugo</a>.
  </span>


      </div>
    </div>

    
    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    
    <script type="text/x-mathjax-config">MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] } });</script>
    
  </body>
</html>
