<!DOCTYPE html>
<html>
  <head>
    
    
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      
  Brep &ndash; Test API Site

    </title>
    
    
    <meta name="description" property="og:description" content="Namespace: Rhino.Geometry
Boundary Representation. A surface or polysurface along with trim curve information.
public class BrepConstructors Brep()  (summary) Initializes a new empty brep (since) 5.4  Properties Collections.BrepCurveList Curves2D  (summary) Parameter space trimming curves (used by trims) (since) 5.6  Collections.BrepCurveList Curves3D  (summary) Pointers to 3d curves (used by edges) (since) 5.6  Collections.BrepEdgeList Edges  (summary) Gets the brep edges list accessor. (since) 5.0  Collections.|">
    

    <meta name="apple-mobile-web-app-title" content="Test API Site">
    
    
    
    


    <link rel="stylesheet" href="/hugo/assets/syntax.css">
    <link rel="stylesheet" href="/hugo/assets/primer-build.css">
    <link rel="stylesheet" href="/hugo/assets/style.css">
  </head>


  <body class="bg-gray">
    <div id="holy" class="container-lg bg-white h-100">

      <div id="header" class="px-1 bg-white">
        <nav class="UnderlineNav UnderlineNav--right px-2">
  <a class="UnderlineNav-actions muted-link h2" href="/hugo/">
    Test API Site
  </a>

  
  
</nav>

      </div>

      <div role="main" id="main" class="holy-main markdown-body px-4 bg-white">
        

<div class="Subhead">
  <div class="Subhead-heading">
    <div class="h1 mt-3 mb-1">Brep</div>
  </div>
  <div class="Subhead-description">
    






    
    <div class="float-md-right">
      <span title="Lastmod: 0001-01-01. Published at: 0001-01-01.">
        
          Published: 0001-01-01
        
      </span>
    </div>
    
  </div>
</div>
<article>
  
  <section class="pb-6 mb-3 border-bottom">
    <p><em>Namespace: <a href="../">Rhino.Geometry</a></em></p>
<p>Boundary Representation. A surface or polysurface along with trim curve information.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-cs" data-lang="cs"><span style="color:#66d9ef">public</span> <span style="color:#66d9ef">class</span> <span style="color:#a6e22e">Brep</span>
</code></pre></div><h2 id="constructors">Constructors</h2>
<h4 id="brep">Brep()</h4>
<ul>
<li>(summary) Initializes a new empty brep</li>
<li>(since) 5.4</li>
</ul>
<h2 id="properties">Properties</h2>
<h4 id="collectionsbrepcurvelist-curves2d">Collections.BrepCurveList Curves2D</h4>
<ul>
<li>(summary) Parameter space trimming curves (used by trims)</li>
<li>(since) 5.6</li>
</ul>
<h4 id="collectionsbrepcurvelist-curves3d">Collections.BrepCurveList Curves3D</h4>
<ul>
<li>(summary) Pointers to 3d curves (used by edges)</li>
<li>(since) 5.6</li>
</ul>
<h4 id="collectionsbrepedgelist-edges">Collections.BrepEdgeList Edges</h4>
<ul>
<li>(summary) Gets the brep edges list accessor.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="collectionsbrepfacelist-faces">Collections.BrepFaceList Faces</h4>
<ul>
<li>(summary) Gets the brep faces list accessor.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="bool-ismanifold">bool IsManifold</h4>
<ul>
<li>(summary) Gets a value indicating whether or not the Brep is manifold. 
Non-Manifold breps have at least one edge that is shared among three or more faces.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="bool-issolid">bool IsSolid</h4>
<ul>
<li>(summary) Determines whether this brep is a solid, or a closed oriented manifold.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="bool-issurface">bool IsSurface</h4>
<ul>
<li>(summary) Returns True if the Brep has a single face and that face is geometrically the same
as the underlying surface.  I.e., the face has trivial trimming.
In this case, the surface is the first face surface. The flag
Brep.Faces[0].OrientationIsReversed records the correspondence between the surface&rsquo;s
natural parametric orientation and the orientation of the Brep.trivial trimming here means that there is only one loop curve in the brep
and that loop curve is the same as the underlying surface boundary.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="collectionsbreplooplist-loops">Collections.BrepLoopList Loops</h4>
<ul>
<li>(summary) Gets the brep loop list accessor.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="brepsolidorientation-solidorientation">BrepSolidOrientation SolidOrientation</h4>
<ul>
<li>(summary) Gets the solid orientation state of this Brep.</li>
<li>(since) 5.0</li>
</ul>
<h4 id="collectionsbrepsurfacelist-surfaces">Collections.BrepSurfaceList Surfaces</h4>
<ul>
<li>(summary) Parametric surfaces used by faces</li>
<li>(since) 5.4</li>
</ul>
<h4 id="collectionsbreptrimlist-trims">Collections.BrepTrimList Trims</h4>
<ul>
<li>(summary) Gets the brep trims list accessor.</li>
<li>(since) 5.1</li>
</ul>
<h4 id="collectionsbrepvertexlist-vertices">Collections.BrepVertexList Vertices</h4>
<ul>
<li>(summary) Gets the brep vertices list accessor.</li>
<li>(since) 5.5</li>
</ul>
<h2 id="methods">Methods</h2>
<h4 id="static-brep-changeseambrepface-faceint-directiondouble-parameterdouble-tolerance">static Brep ChangeSeam(BrepFace face,int direction,double parameter,double tolerance)</h4>
<ul>
<li>(summary) Change the seam of a closed trimmed surface.</li>
<li>(since) 6.4</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-copytrimcurvesbrepface-trimsourcesurface-surfacesourcedouble-tolerance">static Brep CopyTrimCurves(BrepFace trimSource,Surface surfaceSource,double tolerance)</h4>
<ul>
<li>(summary) Copy all trims from a Brep face onto a surface.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createbaseballspherepoint3d-centerdouble-radiusdouble-tolerance">static Brep CreateBaseballSphere(Point3d center,double radius,double tolerance)</h4>
<ul>
<li>(summary) Creates a brep representation of the sphere with two similar trimmed NURBS surfaces, and no singularities.</li>
<li>(since) 6.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-curve-createblendshapebrepface-face0brepedge-edge0double-t0bool-rev0blendcontinuity-continuity0brepface-face1brepedge-edge1double-t1bool-rev1blendcontinuity-continuity1">static Curve CreateBlendShape(BrepFace face0,BrepEdge edge0,double t0,bool rev0,BlendContinuity continuity0,BrepFace face1,BrepEdge edge1,double t1,bool rev1,BlendContinuity continuity1)</h4>
<ul>
<li>(summary) Makes a curve blend between points on two surface edges. The blend will be tangent to the surfaces and perpendicular to the edges.</li>
<li>(since) 6.0</li>
<li>(returns) Curve This is some return comment</li>
</ul>
<h4 id="static-brep-createblendsurfacebrepface-face0brepedge-edge0interval-domain0bool-rev0blendcontinuity-continuity0brepface-face1brepedge-edge1interval-domain1bool-rev1blendcontinuity-continuity1">static Brep[] CreateBlendSurface(BrepFace face0,BrepEdge edge0,Interval domain0,bool rev0,BlendContinuity continuity0,BrepFace face1,BrepEdge edge1,Interval domain1,bool rev1,BlendContinuity continuity1)</h4>
<ul>
<li>(summary) Makes a surface blend between two surface edges.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createbooleandifferencebrep-firstbrepbrep-secondbrepdouble-tolerance">static Brep[] CreateBooleanDifference(Brep firstBrep,Brep secondBrep,double tolerance)</h4>
<ul>
<li>(summary) Compute the Solid Difference of two Breps.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createbooleandifferencebrep-firstbrepbrep-secondbrepdouble-tolerancebool-manifoldonly">static Brep[] CreateBooleanDifference(Brep firstBrep,Brep secondBrep,double tolerance,bool manifoldOnly)</h4>
<ul>
<li>(summary) Compute the Solid Difference of two Breps.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createbooleandifferenceienumerablebrep-firstsetienumerablebrep-secondsetdouble-tolerance">static Brep[] CreateBooleanDifference(IEnumerable<!-- raw HTML omitted --> firstSet,IEnumerable<!-- raw HTML omitted --> secondSet,double tolerance)</h4>
<ul>
<li>(summary) Compute the Solid Difference of two sets of Breps.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createbooleandifferenceienumerablebrep-firstsetienumerablebrep-secondsetdouble-tolerancebool-manifoldonly">static Brep[] CreateBooleanDifference(IEnumerable<!-- raw HTML omitted --> firstSet,IEnumerable<!-- raw HTML omitted --> secondSet,double tolerance,bool manifoldOnly)</h4>
<ul>
<li>(summary) Compute the Solid Difference of two sets of Breps.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createbooleanintersectionbrep-firstbrepbrep-secondbrepdouble-tolerance">static Brep[] CreateBooleanIntersection(Brep firstBrep,Brep secondBrep,double tolerance)</h4>
<ul>
<li>(summary) Compute the Solid Intersection of two Breps.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createbooleanintersectionbrep-firstbrepbrep-secondbrepdouble-tolerancebool-manifoldonly">static Brep[] CreateBooleanIntersection(Brep firstBrep,Brep secondBrep,double tolerance,bool manifoldOnly)</h4>
<ul>
<li>(summary) Compute the Solid Intersection of two Breps.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createbooleanintersectionienumerablebrep-firstsetienumerablebrep-secondsetdouble-tolerance">static Brep[] CreateBooleanIntersection(IEnumerable<!-- raw HTML omitted --> firstSet,IEnumerable<!-- raw HTML omitted --> secondSet,double tolerance)</h4>
<ul>
<li>(summary) Compute the Solid Intersection of two sets of Breps.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createbooleanintersectionienumerablebrep-firstsetienumerablebrep-secondsetdouble-tolerancebool-manifoldonly">static Brep[] CreateBooleanIntersection(IEnumerable<!-- raw HTML omitted --> firstSet,IEnumerable<!-- raw HTML omitted --> secondSet,double tolerance,bool manifoldOnly)</h4>
<ul>
<li>(summary) Compute the Solid Intersection of two sets of Breps.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createbooleansplitbrep-firstbrepbrep-secondbrepdouble-tolerance">static Brep[] CreateBooleanSplit(Brep firstBrep,Brep secondBrep,double tolerance)</h4>
<ul>
<li>(summary) Splits shared areas of Breps and creates separate Breps from the shared and unshared parts.</li>
<li>(since) 6.16</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createbooleansplitienumerablebrep-firstsetienumerablebrep-secondsetdouble-tolerance">static Brep[] CreateBooleanSplit(IEnumerable<!-- raw HTML omitted --> firstSet,IEnumerable<!-- raw HTML omitted --> secondSet,double tolerance)</h4>
<ul>
<li>(summary) Splits shared areas of Breps and creates separate Breps from the shared and unshared parts.</li>
<li>(since) 6.16</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createbooleanunionienumerablebrep-brepsdouble-tolerance">static Brep[] CreateBooleanUnion(IEnumerable<!-- raw HTML omitted --> breps,double tolerance)</h4>
<ul>
<li>(summary) Compute the Boolean Union of a set of Breps.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createbooleanunionienumerablebrep-brepsdouble-tolerancebool-manifoldonly">static Brep[] CreateBooleanUnion(IEnumerable<!-- raw HTML omitted --> breps,double tolerance,bool manifoldOnly)</h4>
<ul>
<li>(summary) Compute the Boolean Union of a set of Breps.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createchamfersurfacebrepface-face0point2d-uv0double-radius0brepface-face1point2d-uv1double-radius1bool-trimbool-extenddouble-tolerancebrep-outbreps0brep-outbreps1">static Brep[] CreateChamferSurface(BrepFace face0,Point2d uv0,double radius0,BrepFace face1,Point2d uv1,double radius1,bool trim,bool extend,double tolerance,Brep[] outBreps0,Brep[] outBreps1)</h4>
<ul>
<li>(summary) Creates a ruled surface as a bevel between two input surface edges.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createchamfersurfacebrepface-face0point2d-uv0double-radius0brepface-face1point2d-uv1double-radius1bool-extenddouble-tolerance">static Brep[] CreateChamferSurface(BrepFace face0,Point2d uv0,double radius0,BrepFace face1,Point2d uv1,double radius1,bool extend,double tolerance)</h4>
<ul>
<li>(summary) Creates a ruled surface as a bevel between two input surface edges.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-curve-createcontourcurvesbrep-breptocontourplane-sectionplane">static Curve[] CreateContourCurves(Brep brepToContour,Plane sectionPlane)</h4>
<ul>
<li>(summary) Constructs the contour curves for a brep, using a slicing plane.</li>
<li>(since) 5.0</li>
<li>(returns) Curve[] This is some return comment</li>
</ul>
<h4 id="static-curve-createcontourcurvesbrep-breptocontourpoint3d-contourstartpoint3d-contourenddouble-interval">static Curve[] CreateContourCurves(Brep brepToContour,Point3d contourStart,Point3d contourEnd,double interval)</h4>
<ul>
<li>(summary) Constructs the contour curves for a brep at a specified interval.</li>
<li>(since) 5.0</li>
<li>(returns) Curve[] This is some return comment</li>
</ul>
<h4 id="static-mesh-createcurvatureanalysismeshbrep-brepcurvatureanalysissettingsstate-state">static Mesh[] CreateCurvatureAnalysisMesh(Brep brep,CurvatureAnalysisSettingsState state)</h4>
<ul>
<li>(summary) Create an array of analysis meshes for the brep using the specified settings.
Meshes aren&rsquo;t set on the brep.</li>
<li>(since) 6.0</li>
<li>(returns) Mesh[] This is some return comment</li>
</ul>
<h4 id="static-brep-createdevelopableloftcurve-crv0curve-crv1bool-reverse0bool-reverse1int-density">static Brep[] CreateDevelopableLoft(Curve crv0,Curve crv1,bool reverse0,bool reverse1,int density)</h4>
<ul>
<li>(summary) Creates a single developable surface between two curves.</li>
<li>(since) 6.10</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createdevelopableloftnurbscurve-rail0nurbscurve-rail1ienumerablepoint2d-fixedrulings">static Brep[] CreateDevelopableLoft(NurbsCurve rail0,NurbsCurve rail1,IEnumerable<!-- raw HTML omitted --> fixedRulings)</h4>
<ul>
<li>(summary) Creates a single developable surface between two curves.</li>
<li>(since) 6.10</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createedgesurfaceienumerablecurve-curves">static Brep CreateEdgeSurface(IEnumerable<!-- raw HTML omitted --> curves)</h4>
<ul>
<li>(summary) Constructs a coons patch from 2, 3, or 4 curves.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createfilletedgesbrep-brepienumerableint-edgeindicesienumerabledouble-startradiiienumerabledouble-endradiiblendtype-blendtyperailtype-railtypedouble-tolerance">static Brep[] CreateFilletEdges(Brep brep,IEnumerable<!-- raw HTML omitted --> edgeIndices,IEnumerable<!-- raw HTML omitted --> startRadii,IEnumerable<!-- raw HTML omitted --> endRadii,BlendType blendType,RailType railType,double tolerance)</h4>
<ul>
<li>(summary) Fillets, chamfers, or blends the edges of a brep.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfilletsurfacebrepface-face0point2d-uv0brepface-face1point2d-uv1double-radiusbool-trimbool-extenddouble-tolerancebrep-outbreps0brep-outbreps1">static Brep[] CreateFilletSurface(BrepFace face0,Point2d uv0,BrepFace face1,Point2d uv1,double radius,bool trim,bool extend,double tolerance,Brep[] outBreps0,Brep[] outBreps1)</h4>
<ul>
<li>(summary) Creates a constant-radius round surface between two surfaces.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfilletsurfacebrepface-face0point2d-uv0brepface-face1point2d-uv1double-radiusbool-extenddouble-tolerance">static Brep[] CreateFilletSurface(BrepFace face0,Point2d uv0,BrepFace face1,Point2d uv1,double radius,bool extend,double tolerance)</h4>
<ul>
<li>(summary) Creates a constant-radius round surface between two surfaces.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfromboxboundingbox-box">static Brep CreateFromBox(BoundingBox box)</h4>
<ul>
<li>(summary) Constructs new brep that matches a bounding box.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createfromboxbox-box">static Brep CreateFromBox(Box box)</h4>
<ul>
<li>(summary) Constructs new brep that matches an aligned box.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createfromboxienumerablepoint3d-corners">static Brep CreateFromBox(IEnumerable<!-- raw HTML omitted --> corners)</h4>
<ul>
<li>(summary) Constructs new brep from 8 corner points.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createfromconecone-conebool-capbottom">static Brep CreateFromCone(Cone cone,bool capBottom)</h4>
<ul>
<li>(summary) Constructs a Brep representation of the cone with a single
face for the cone, an edge along the cone seam, 
and vertices at the base and apex ends of this seam edge.
The optional cap is a single face with one circular edge 
starting and ending at the base vertex.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createfromcornerpointspoint3d-corner1point3d-corner2point3d-corner3double-tolerance">static Brep CreateFromCornerPoints(Point3d corner1,Point3d corner2,Point3d corner3,double tolerance)</h4>
<ul>
<li>(summary) Makes a brep with one face.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createfromcornerpointspoint3d-corner1point3d-corner2point3d-corner3point3d-corner4double-tolerance">static Brep CreateFromCornerPoints(Point3d corner1,Point3d corner2,Point3d corner3,Point3d corner4,double tolerance)</h4>
<ul>
<li>(summary) make a Brep with one face.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createfromcylindercylinder-cylinderbool-capbottombool-captop">static Brep CreateFromCylinder(Cylinder cylinder,bool capBottom,bool capTop)</h4>
<ul>
<li>(summary) Constructs a Brep definition of a cylinder.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createfromjoinededgesbrep-brep0int-edgeindex0brep-brep1int-edgeindex1double-jointolerance">static Brep CreateFromJoinedEdges(Brep brep0,int edgeIndex0,Brep brep1,int edgeIndex1,double joinTolerance)</h4>
<ul>
<li>(summary) Joins two naked edges, or edges that are coincident or close together, from two Breps.</li>
<li>(since) 6.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createfromloftienumerablecurve-curvespoint3d-startpoint3d-endlofttype-lofttypebool-closed">static Brep[] CreateFromLoft(IEnumerable<!-- raw HTML omitted --> curves,Point3d start,Point3d end,LoftType loftType,bool closed)</h4>
<ul>
<li>(summary) Constructs one or more Breps by lofting through a set of curves.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfromloftrebuildienumerablecurve-curvespoint3d-startpoint3d-endlofttype-lofttypebool-closedint-rebuildpointcount">static Brep[] CreateFromLoftRebuild(IEnumerable<!-- raw HTML omitted --> curves,Point3d start,Point3d end,LoftType loftType,bool closed,int rebuildPointCount)</h4>
<ul>
<li>(summary) Constructs one or more Breps by lofting through a set of curves. Input for the loft is simplified by
rebuilding to a specified number of control points.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfromloftrefitienumerablecurve-curvespoint3d-startpoint3d-endlofttype-lofttypebool-closeddouble-refittolerance">static Brep[] CreateFromLoftRefit(IEnumerable<!-- raw HTML omitted --> curves,Point3d start,Point3d end,LoftType loftType,bool closed,double refitTolerance)</h4>
<ul>
<li>(summary) Constructs one or more Breps by lofting through a set of curves. Input for the loft is simplified by
refitting to a specified tolerance.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfrommeshmesh-meshbool-trimmedtriangles">static Brep CreateFromMesh(Mesh mesh,bool trimmedTriangles)</h4>
<ul>
<li>(summary) Create a brep representation of a mesh</li>
<li>(since) 5.1</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createfromoffsetfacebrepface-facedouble-offsetdistancedouble-offsettolerancebool-bothsidesbool-createsolid">static Brep CreateFromOffsetFace(BrepFace face,double offsetDistance,double offsetTolerance,bool bothSides,bool createSolid)</h4>
<ul>
<li>(summary) Offsets a face including trim information to create a new brep.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createfromrevsurfacerevsurface-surfacebool-capstartbool-capend">static Brep CreateFromRevSurface(RevSurface surface,bool capStart,bool capEnd)</h4>
<ul>
<li>(summary) Constructs a brep form of a surface of revolution.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createfromspheresphere-sphere">static Brep CreateFromSphere(Sphere sphere)</h4>
<ul>
<li>(summary) Constructs a Brep definition of a sphere.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createfromsurfacesurface-surface">static Brep CreateFromSurface(Surface surface)</h4>
<ul>
<li>(summary) Constructs a Brep from a surface. The resulting Brep has an outer boundary made
from four trims. The trims are ordered so that they run along the south, east,
north, and then west side of the surface&rsquo;s parameter space.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createfromsweepcurve-railcurve-shapebool-closeddouble-tolerance">static Brep[] CreateFromSweep(Curve rail,Curve shape,bool closed,double tolerance)</h4>
<ul>
<li>(summary) Sweep1 function that fits a surface through a profile curve that define the surface cross-sections
and one curve that defines a surface edge.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfromsweepcurve-rail1curve-rail2curve-shapebool-closeddouble-tolerance">static Brep[] CreateFromSweep(Curve rail1,Curve rail2,Curve shape,bool closed,double tolerance)</h4>
<ul>
<li>(summary) General 2 rail sweep. If you are not producing the sweep results that you are after, then
use the SweepTwoRail class with options to generate the swept geometry.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfromsweepcurve-rail1curve-rail2ienumerablecurve-shapesbool-closeddouble-tolerance">static Brep[] CreateFromSweep(Curve rail1,Curve rail2,IEnumerable<!-- raw HTML omitted --> shapes,bool closed,double tolerance)</h4>
<ul>
<li>(summary) General 2 rail sweep. If you are not producing the sweep results that you are after, then
use the SweepTwoRail class with options to generate the swept geometry.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfromsweepcurve-rail1curve-rail2ienumerablecurve-shapespoint3d-startpoint3d-endbool-closeddouble-tolerancesweeprebuild-rebuildint-rebuildpointcountdouble-refittolerancebool-preserveheight">static Brep[] CreateFromSweep(Curve rail1,Curve rail2,IEnumerable<!-- raw HTML omitted --> shapes,Point3d start,Point3d end,bool closed,double tolerance,SweepRebuild rebuild,int rebuildPointCount,double refitTolerance,bool preserveHeight)</h4>
<ul>
<li>(summary) Sweep2 function that fits a surface through profile curves that define the surface cross-sections
and two curves that defines a surface edge.</li>
<li>(since) 6.16</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfromsweepcurve-railienumerablecurve-shapesbool-closeddouble-tolerance">static Brep[] CreateFromSweep(Curve rail,IEnumerable<!-- raw HTML omitted --> shapes,bool closed,double tolerance)</h4>
<ul>
<li>(summary) Sweep1 function that fits a surface through profile curves that define the surface cross-sections
and one curve that defines a surface edge.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfromsweepinpartscurve-rail1curve-rail2ienumerablecurve-shapesienumerablepoint2d-rail_paramsbool-closeddouble-tolerance">static Brep[] CreateFromSweepInParts(Curve rail1,Curve rail2,IEnumerable<!-- raw HTML omitted --> shapes,IEnumerable<!-- raw HTML omitted --> rail_params,bool closed,double tolerance)</h4>
<ul>
<li>(summary) Makes a 2 rail sweep. Like CreateFromSweep but the result is split where parameterization along a rail changes abruptly.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfromsweepsegmentedcurve-railcurve-shapebool-closeddouble-tolerance">static Brep[] CreateFromSweepSegmented(Curve rail,Curve shape,bool closed,double tolerance)</h4>
<ul>
<li>(summary) Sweep1 function that fits a surface through a profile curve that define the surface cross-sections
and one curve that defines a surface edge. The Segmented version breaks the rail at curvature kinks
and sweeps each piece separately, then put the results together into a Brep.</li>
<li>(since) 6.14</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfromsweepsegmentedcurve-railienumerablecurve-shapesbool-closeddouble-tolerance">static Brep[] CreateFromSweepSegmented(Curve rail,IEnumerable<!-- raw HTML omitted --> shapes,bool closed,double tolerance)</h4>
<ul>
<li>(summary) Sweep1 function that fits a surface through a series of profile curves that define the surface cross-sections
and one curve that defines a surface edge. The Segmented version breaks the rail at curvature kinks
and sweeps each piece separately, then put the results together into a Brep.</li>
<li>(since) 6.14</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfromtaperedextrudecurve-curvetoextrudedouble-distancevector3d-directionpoint3d-basepointdouble-draftangleradiansextrudecornertype-cornertype">static Brep[] CreateFromTaperedExtrude(Curve curveToExtrude,double distance,Vector3d direction,Point3d basePoint,double draftAngleRadians,ExtrudeCornerType cornerType)</h4>
<ul>
<li>(summary) Extrude a curve to a taper making a brep (potentially more than 1)</li>
<li>(since) 5.1</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfromtaperedextrudecurve-curvetoextrudedouble-distancevector3d-directionpoint3d-basepointdouble-draftangleradiansextrudecornertype-cornertypedouble-tolerancedouble-angletoleranceradians">static Brep[] CreateFromTaperedExtrude(Curve curveToExtrude,double distance,Vector3d direction,Point3d basePoint,double draftAngleRadians,ExtrudeCornerType cornerType,double tolerance,double angleToleranceRadians)</h4>
<ul>
<li>(summary) Extrude a curve to a taper making a brep (potentially more than 1)</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createfromtaperedextrudewithrefcurve-curvevector3d-directiondouble-distancedouble-draftangleplane-planedouble-tolerance">static Brep[] CreateFromTaperedExtrudeWithRef(Curve curve,Vector3d direction,double distance,double draftAngle,Plane plane,double tolerance)</h4>
<ul>
<li>(summary) Creates one or more Breps by extruding a curve a distance along an axis with draft angle.</li>
<li>(since) 6.14</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createoffsetbrepbrep-brepdouble-distancebool-solidbool-extenddouble-tolerancebrep-outblendsbrep-outwalls">static Brep[] CreateOffsetBrep(Brep brep,double distance,bool solid,bool extend,double tolerance,Brep[] outBlends,Brep[] outWalls)</h4>
<ul>
<li>(summary) Offsets a Brep.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createpatchienumerablegeometrybase-geometryint-uspansint-vspansdouble-tolerance">static Brep CreatePatch(IEnumerable<!-- raw HTML omitted --> geometry,int uSpans,int vSpans,double tolerance)</h4>
<ul>
<li>(summary) Constructs a brep patch.
This is the simple version of fit that uses a plane with u x v spans.
It makes a plane by fitting to the points from the input geometry to use as the starting surface.
The surface has the specified u and v span count.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createpatchienumerablegeometrybase-geometrysurface-startingsurfacedouble-tolerance">static Brep CreatePatch(IEnumerable<!-- raw HTML omitted --> geometry,Surface startingSurface,double tolerance)</h4>
<ul>
<li>(summary) Constructs a brep patch.
This is the simple version of fit that uses a specified starting surface.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createpatchienumerablegeometrybase-geometrysurface-startingsurfaceint-uspansint-vspansbool-trimbool-tangencydouble-pointspacingdouble-flexibilitydouble-surfacepullbool-fixedgesdouble-tolerance">static Brep CreatePatch(IEnumerable<!-- raw HTML omitted --> geometry,Surface startingSurface,int uSpans,int vSpans,bool trim,bool tangency,double pointSpacing,double flexibility,double surfacePull,bool[] fixEdges,double tolerance)</h4>
<ul>
<li>(summary) Constructs a brep patch using all controls</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createpipecurve-raildouble-radiusbool-localblendingpipecapmode-capbool-fitraildouble-absolutetolerancedouble-angletoleranceradians">static Brep[] CreatePipe(Curve rail,double radius,bool localBlending,PipeCapMode cap,bool fitRail,double absoluteTolerance,double angleToleranceRadians)</h4>
<ul>
<li>(summary) Creates a single walled pipe</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createpipecurve-railienumerabledouble-railradiiparametersienumerabledouble-radiibool-localblendingpipecapmode-capbool-fitraildouble-absolutetolerancedouble-angletoleranceradians">static Brep[] CreatePipe(Curve rail,IEnumerable<!-- raw HTML omitted --> railRadiiParameters,IEnumerable<!-- raw HTML omitted --> radii,bool localBlending,PipeCapMode cap,bool fitRail,double absoluteTolerance,double angleToleranceRadians)</h4>
<ul>
<li>(summary) Creates a single walled pipe</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createplanarbrepscurve-inputloop">static Brep[] CreatePlanarBreps(Curve inputLoop)</h4>
<ul>
<li>(summary) Constructs a set of planar breps as outlines by the loops.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createplanarbrepscurve-inputloopdouble-tolerance">static Brep[] CreatePlanarBreps(Curve inputLoop,double tolerance)</h4>
<ul>
<li>(summary) Constructs a set of planar breps as outlines by the loops.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createplanarbrepscurvelist-inputloops">static Brep[] CreatePlanarBreps(CurveList inputLoops)</h4>
<ul>
<li>(summary) Constructs a set of planar Breps as outlines by the loops.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createplanarbrepscurvelist-inputloopsdouble-tolerance">static Brep[] CreatePlanarBreps(CurveList inputLoops,double tolerance)</h4>
<ul>
<li>(summary) Constructs a set of planar Breps as outlines by the loops.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createplanarbrepsienumerablecurve-inputloops">static Brep[] CreatePlanarBreps(IEnumerable<!-- raw HTML omitted --> inputLoops)</h4>
<ul>
<li>(summary) Constructs a set of planar breps as outlines by the loops.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createplanarbrepsienumerablecurve-inputloopsdouble-tolerance">static Brep[] CreatePlanarBreps(IEnumerable<!-- raw HTML omitted --> inputLoops,double tolerance)</h4>
<ul>
<li>(summary) Constructs a set of planar breps as outlines by the loops.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createquadspheresphere-sphere">static Brep CreateQuadSphere(Sphere sphere)</h4>
<ul>
<li>(summary) Constructs a Brep definition of a quad sphere.</li>
<li>(since) 6.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createshellbrep-brepienumerableint-facestoremovedouble-distancedouble-tolerance">static Brep[] CreateShell(Brep brep,IEnumerable<!-- raw HTML omitted --> facesToRemove,double distance,double tolerance)</h4>
<ul>
<li>(summary) Creates a hollowed out shell from a solid Brep. Function only operates on simple, solid, manifold Breps.</li>
<li>(since) 5.4</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createsolidienumerablebrep-brepsdouble-tolerance">static Brep[] CreateSolid(IEnumerable<!-- raw HTML omitted --> breps,double tolerance)</h4>
<ul>
<li>(summary) Constructs closed polysurfaces from surfaces and polysurfaces that bound a region in space.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-createtrimmedplaneplane-planecurve-curve">static Brep CreateTrimmedPlane(Plane plane,Curve curve)</h4>
<ul>
<li>(summary) Create a Brep trimmed plane.</li>
<li>(since) 6.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createtrimmedplaneplane-planeienumerablecurve-curves">static Brep CreateTrimmedPlane(Plane plane,IEnumerable<!-- raw HTML omitted --> curves)</h4>
<ul>
<li>(summary) Create a Brep trimmed plane.</li>
<li>(since) 6.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createtrimmedsurfacebrepface-trimsourcesurface-surfacesource">static Brep CreateTrimmedSurface(BrepFace trimSource,Surface surfaceSource)</h4>
<ul>
<li>(summary) Constructs a Brep using the trimming information of a brep face and a surface. 
Surface must be roughly the same shape and in the same location as the trimming brep face.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-createtrimmedsurfacebrepface-trimsourcesurface-surfacesourcedouble-tolerance">static Brep CreateTrimmedSurface(BrepFace trimSource,Surface surfaceSource,double tolerance)</h4>
<ul>
<li>(summary) Constructs a Brep using the trimming information of a brep face and a surface. 
Surface must be roughly the same shape and in the same location as the trimming brep face.</li>
<li>(since) 6.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-joinbrepsienumerablebrep-brepstojoindouble-tolerance">static Brep[] JoinBreps(IEnumerable<!-- raw HTML omitted --> brepsToJoin,double tolerance)</h4>
<ul>
<li>(summary) Joins the breps in the input array at any overlapping edges to form
as few as possible resulting breps. There may be more than one brep in the result array.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="static-brep-mergebrepsienumerablebrep-brepstomergedouble-tolerance">static Brep MergeBreps(IEnumerable<!-- raw HTML omitted --> brepsToMerge,double tolerance)</h4>
<ul>
<li>(summary) Combines two or more breps into one. A merge is like a boolean union that keeps the inside pieces. This
function creates non-manifold Breps which in general are unusual in Rhino. You may want to consider using
JoinBreps or CreateBooleanUnion functions instead.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-mergesurfacesbrep-brep0brep-brep1double-tolerancedouble-angletoleranceradians">static Brep MergeSurfaces(Brep brep0,Brep brep1,double tolerance,double angleToleranceRadians)</h4>
<ul>
<li>(summary) Merges two surfaces into one surface at untrimmed edges. Both surfaces must be untrimmed and share an edge.</li>
<li>(since) 6.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-mergesurfacesbrep-brep0brep-brep1double-tolerancedouble-angletoleranceradianspoint2d-point0point2d-point1double-roundnessbool-smooth">static Brep MergeSurfaces(Brep brep0,Brep brep1,double tolerance,double angleToleranceRadians,Point2d point0,Point2d point1,double roundness,bool smooth)</h4>
<ul>
<li>(summary) Merges two surfaces into one surface at untrimmed edges. Both surfaces must be untrimmed and share an edge.</li>
<li>(since) 6.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-mergesurfacessurface-surface0surface-surface1double-tolerancedouble-angletoleranceradians">static Brep MergeSurfaces(Surface surface0,Surface surface1,double tolerance,double angleToleranceRadians)</h4>
<ul>
<li>(summary) Merges two surfaces into one surface at untrimmed edges.</li>
<li>(since) 6.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="static-brep-tryconvertbrepgeometrybase-geometry">static Brep TryConvertBrep(GeometryBase geometry)</h4>
<ul>
<li>(summary) Attempts to convert a generic Geometry object into a Brep.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="int-addedgecurvecurve-curve">int AddEdgeCurve(Curve curve)</h4>
<ul>
<li>(summary) Add a 3d curve used by the brep edges</li>
<li>(since) 5.4</li>
<li>(returns) int This is some return comment</li>
</ul>
<h4 id="int-addsurfacesurface-surface">int AddSurface(Surface surface)</h4>
<ul>
<li>(summary) Adds a 3D surface used by BrepFace.</li>
<li>(since) 5.0</li>
<li>(returns) int This is some return comment</li>
</ul>
<h4 id="int-addtrimcurvecurve-curve">int AddTrimCurve(Curve curve)</h4>
<ul>
<li>(summary) Add a 2d curve used by the brep trims</li>
<li>(since) 5.4</li>
<li>(returns) int This is some return comment</li>
</ul>
<h4 id="void-appendbrep-other">void Append(Brep other)</h4>
<ul>
<li>(summary) Appends a copy of another brep to this and updates indices of appended
brep parts.  Duplicates are not removed</li>
<li>(since) 5.4</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="brep-capplanarholesdouble-tolerance">Brep CapPlanarHoles(double tolerance)</h4>
<ul>
<li>(summary) Returns a new Brep that is equivalent to this Brep with all planar holes capped.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="point3d-closestpointpoint3d-testpoint">Point3d ClosestPoint(Point3d testPoint)</h4>
<ul>
<li>(summary) Finds a point on the brep that is closest to testPoint.</li>
<li>(since) 5.0</li>
<li>(returns) Point3d This is some return comment</li>
</ul>
<h4 id="bool-closestpointpoint3d-testpointpoint3d-closestpointcomponentindex-cidouble-sdouble-tdouble-maximumdistancevector3d-normal">bool ClosestPoint(Point3d testPoint,Point3d closestPoint,ComponentIndex ci,double s,double t,double maximumDistance,Vector3d normal)</h4>
<ul>
<li>(summary) Finds a point on a Brep that is closest to testPoint.
The method searches all Brep faces looking for the one closest to testPoint.
When found, if the closest point falls on the inactive region of the face, then 
the method finds the face&rsquo;s edge that is closest to testPoint.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="void-compact">void Compact()</h4>
<ul>
<li>(summary) Deletes any unreferenced objects from arrays, reindexes as needed, and
shrinks arrays to minimum required size. Uses CUllUnused* members to
delete any unreferenced objects from arrays.</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="bool-cullunused2dcurves">bool CullUnused2dCurves()</h4>
<ul>
<li>(summary) Culls 3d curves not referenced by an edge.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-cullunused3dcurves">bool CullUnused3dCurves()</h4>
<ul>
<li>(summary) Culls 2d curves not referenced by a trim.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-cullunusededges">bool CullUnusedEdges()</h4>
<ul>
<li>(summary) Culls edges with m_edge_index == -1.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-cullunusedfaces">bool CullUnusedFaces()</h4>
<ul>
<li>(summary) Culls faces with m_face_index == -1.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-cullunusedloops">bool CullUnusedLoops()</h4>
<ul>
<li>(summary) Culls loops with m_loop_index == -1.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-cullunusedsurfaces">bool CullUnusedSurfaces()</h4>
<ul>
<li>(summary) Culls surfaces not referenced by a face.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-cullunusedtrims">bool CullUnusedTrims()</h4>
<ul>
<li>(summary) Culls trims with m_trim_index == -1.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-cullunusedvertices">bool CullUnusedVertices()</h4>
<ul>
<li>(summary) Culls vertices with m_vertex_index == -1.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="geometrybase-duplicate">GeometryBase Duplicate()</h4>
<ul>
<li>(summary) Copies this brep.</li>
<li>(since) 5.0</li>
<li>(returns) GeometryBase This is some return comment</li>
</ul>
<h4 id="brep-duplicatebrep">Brep DuplicateBrep()</h4>
<ul>
<li>(summary) Same as , but already performs a cast to a brep.
This cast always succeeds.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="curve-duplicateedgecurves">Curve[] DuplicateEdgeCurves()</h4>
<ul>
<li>(summary) Duplicate all the edges of this Brep.</li>
<li>(since) 5.0</li>
<li>(returns) Curve[] This is some return comment</li>
</ul>
<h4 id="curve-duplicateedgecurvesbool-nakedonly">Curve[] DuplicateEdgeCurves(bool nakedOnly)</h4>
<ul>
<li>(summary) Duplicate edges of this Brep.</li>
<li>(since) 5.0</li>
<li>(returns) Curve[] This is some return comment</li>
</ul>
<h4 id="curve-duplicatenakededgecurvesbool-outerbool-inner">Curve[] DuplicateNakedEdgeCurves(bool outer,bool inner)</h4>
<ul>
<li>(summary) Duplicate naked edges of this Brep</li>
<li>(since) 5.7</li>
<li>(returns) Curve[] This is some return comment</li>
</ul>
<h4 id="brep-duplicatesubbrepienumerableint-faceindices">Brep DuplicateSubBrep(IEnumerable<!-- raw HTML omitted --> faceIndices)</h4>
<ul>
<li>(summary) Copy a subset of this Brep into another Brep.</li>
<li>(since) 5.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="point3d-duplicatevertices">Point3d[] DuplicateVertices()</h4>
<ul>
<li>(summary) Duplicate all the corner vertices of this Brep.</li>
<li>(since) 5.0</li>
<li>(returns) Point3d[] This is some return comment</li>
</ul>
<h4 id="void-findcoincidentbrepcomponentspoint3d-pointdouble-toleranceint-facesint-edgesint-vertices">void FindCoincidentBrepComponents(Point3d point,double tolerance,int[] faces,int[] edges,int[] vertices)</h4>
<ul>
<li>(summary) Find the indices of all brep faces, edges and vertices that are within tolerance of a test-point.</li>
<li>(since) 6.2</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="void-flip">void Flip()</h4>
<ul>
<li>(summary) Reverses entire brep orientation of all faces.</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="double-getarea">double GetArea()</h4>
<ul>
<li>(summary) Compute the Area of the Brep. If you want proper Area data with moments 
and error information, use the AreaMassProperties class.</li>
<li>(since) 5.0</li>
<li>(returns) double This is some return comment</li>
</ul>
<h4 id="double-getareadouble-relativetolerancedouble-absolutetolerance">double GetArea(double relativeTolerance,double absoluteTolerance)</h4>
<ul>
<li>(summary) Compute the Area of the Brep. If you want proper Area data with moments 
and error information, use the AreaMassProperties class.</li>
<li>(since) 5.0</li>
<li>(returns) double This is some return comment</li>
</ul>
<h4 id="bool-getpointinsidedouble-tolerancepoint3d-point">bool GetPointInside(double tolerance,Point3d point)</h4>
<ul>
<li>(summary) Finds a point inside of a solid Brep.</li>
<li>(since) 6.19</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="brepregion-getregions">BrepRegion[] GetRegions()</h4>
<ul>
<li>(summary) Gets an array containing all regions in this brep.</li>
<li>(since) 5.0</li>
<li>(returns) BrepRegion[] This is some return comment</li>
</ul>
<h4 id="double-getvolume">double GetVolume()</h4>
<ul>
<li>(summary) Compute the Volume of the Brep. If you want proper Volume data with moments 
and error information, use the VolumeMassProperties class.</li>
<li>(since) 5.0</li>
<li>(returns) double This is some return comment</li>
</ul>
<h4 id="double-getvolumedouble-relativetolerancedouble-absolutetolerance">double GetVolume(double relativeTolerance,double absoluteTolerance)</h4>
<ul>
<li>(summary) Compute the Volume of the Brep. If you want proper Volume data with moments 
and error information, use the VolumeMassProperties class.</li>
<li>(since) 5.0</li>
<li>(returns) double This is some return comment</li>
</ul>
<h4 id="curve-getwireframeint-density">Curve[] GetWireframe(int density)</h4>
<ul>
<li>(summary) Constructs all the Wireframe curves for this Brep.</li>
<li>(since) 5.0</li>
<li>(returns) Curve[] This is some return comment</li>
</ul>
<h4 id="bool-isduplicatebrep-otherdouble-tolerance">bool IsDuplicate(Brep other,double tolerance)</h4>
<ul>
<li>(summary) See if this and other are same brep geometry.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-ispointinsidepoint3d-pointdouble-tolerancebool-strictlyin">bool IsPointInside(Point3d point,double tolerance,bool strictlyIn)</h4>
<ul>
<li>(summary) Determines if point is inside a Brep.  This question only makes sense when
the brep is a closed and manifold.  This function does not not check for
closed or manifold, so result is not valid in those cases.  Intersects
a line through point with brep, finds the intersection point Q closest
to point, and looks at face normal at Q.  If the point Q is on an edge
or the intersection is not transverse at Q, then another line is used.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-isvalidgeometrystring-log">bool IsValidGeometry(string log)</h4>
<ul>
<li>(summary) Expert user function that tests the brep to see if its geometry information is valid.
The value of brep.IsValidTopology() must be True before brep.IsValidGeometry() can be
safely called.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-isvalidtolerancesandflagsstring-log">bool IsValidTolerancesAndFlags(string log)</h4>
<ul>
<li>(summary) Expert user function that tests the brep to see if its tolerances and
flags are valid.  The values of brep.IsValidTopology() and
brep.IsValidGeometry() must be True before brep.IsValidTolerancesAndFlags()
can be safely called.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-isvalidtopologystring-log">bool IsValidTopology(string log)</h4>
<ul>
<li>(summary) Tests the brep to see if its topology information is valid.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-joinbrep-otherbrepdouble-tolerancebool-compact">bool Join(Brep otherBrep,double tolerance,bool compact)</h4>
<ul>
<li>(summary) If any edges of this brep overlap edges of otherBrep, merge a copy of otherBrep into this
brep joining all edges that overlap within tolerance.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-joinedgesint-edgeindex0int-edgeindex1double-jointolerancebool-compact">bool JoinEdges(int edgeIndex0,int edgeIndex1,double joinTolerance,bool compact)</h4>
<ul>
<li>(summary) Joins two naked edges, or edges that are coincident or close together.</li>
<li>(since) 6.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="int-joinnakededgesdouble-tolerance">int JoinNakedEdges(double tolerance)</h4>
<ul>
<li>(summary) Joins naked edge pairs within the same brep that overlap within tolerance.</li>
<li>(since) 5.0</li>
<li>(returns) int This is some return comment</li>
</ul>
<h4 id="bool-makevalidforv2">bool MakeValidForV2()</h4>
<ul>
<li>(summary) No support is available for this function.
Expert user function that converts all geometry in brep to nurbs form.</li>
<li>(since) 6.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-mergecoplanarfacesdouble-tolerance">bool MergeCoplanarFaces(double tolerance)</h4>
<ul>
<li>(summary) Merges adjacent coplanar faces into single faces.</li>
<li>(since) 5.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="bool-mergecoplanarfacesdouble-tolerancedouble-angletolerance">bool MergeCoplanarFaces(double tolerance,double angleTolerance)</h4>
<ul>
<li>(summary) Merges adjacent coplanar faces into single faces.</li>
<li>(since) 6.10</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="void-rebuildtrimsforv2brepface-facenurbssurface-nurbssurface">void RebuildTrimsForV2(BrepFace face,NurbsSurface nurbsSurface)</h4>
<ul>
<li>(summary) No support is available for this function.
Expert user function used by MakeValidForV2 to convert trim
curves from one surface to its NURBS form. After calling this function,
you need to change the surface of the face to a NurbsSurface.</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="bool-removefins">bool RemoveFins()</h4>
<ul>
<li>(summary) Recursively removes any Brep face with a naked edge. This function is only useful for non-manifold Breps.</li>
<li>(since) 7.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="brep-removeholesdouble-tolerance">Brep RemoveHoles(double tolerance)</h4>
<ul>
<li>(summary) Remove all inner loops, or holes, in a Brep.</li>
<li>(since) 6.0</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="brep-removeholesienumerablecomponentindex-loopsdouble-tolerance">Brep RemoveHoles(IEnumerable<!-- raw HTML omitted --> loops,double tolerance)</h4>
<ul>
<li>(summary) Removes inner loops, or holes, in a Brep.</li>
<li>(since) 6.8</li>
<li>(returns) Brep This is some return comment</li>
</ul>
<h4 id="bool-repairdouble-tolerance">bool Repair(double tolerance)</h4>
<ul>
<li>(summary) Fills in missing or fixes incorrect component information from a Brep. 
Useful when reading Brep information from other file formats that do not 
provide as complete of a Brep definition as requried by Rhino.</li>
<li>(since) 6.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="void-settolerancesboxesandflags">void SetTolerancesBoxesAndFlags()</h4>
<ul>
<li>(summary) Set tolerances and flags in a Brep.</li>
<li>(since) 6.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="void-settolerancesboxesandflagsbool-blazybool-bsetvertextolerancesbool-bsetedgetolerancesbool-bsettrimtolerancesbool-bsettrimisoflagsbool-bsettrimtypeflagsbool-bsetlooptypeflagsbool-bsettrimboxes">void SetTolerancesBoxesAndFlags(bool bLazy,bool bSetVertexTolerances,bool bSetEdgeTolerances,bool bSetTrimTolerances,bool bSetTrimIsoFlags,bool bSetTrimTypeFlags,bool bSetLoopTypeFlags,bool bSetTrimBoxes)</h4>
<ul>
<li>(summary) Set tolerances and flags in a Brep.</li>
<li>(since) 6.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="void-settrimisoflags">void SetTrimIsoFlags()</h4>
<ul>
<li>(summary) This function can be used to set the BrepTrim::m_iso
flag. It is intended to be used when creating a Brep from
a definition that does not include compatible parameter space
type information.</li>
<li>(since) 5.4</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="void-setvertices">void SetVertices()</h4>
<ul>
<li>(summary) This function can be used to compute vertex information for a
b-rep when everything but the Vertices array is properly filled in.
It is intended to be used when creating a Brep from a 
definition that does not include explicit vertex information.</li>
<li>(since) 5.4</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="brep-splitbrep-cutterdouble-intersectiontolerance">Brep[] Split(Brep cutter,double intersectionTolerance)</h4>
<ul>
<li>(summary) Splits a Brep into pieces using a Brep as a cutter.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="brep-splitbrep-cutterdouble-intersectiontolerancebool-tolerancewasraised">Brep[] Split(Brep cutter,double intersectionTolerance,bool toleranceWasRaised)</h4>
<ul>
<li>(summary) Splits a Brep into pieces using a Brep as a cutter.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="brep-splitienumerablebrep-cuttersdouble-intersectiontolerance">Brep[] Split(IEnumerable<!-- raw HTML omitted --> cutters,double intersectionTolerance)</h4>
<ul>
<li>(summary) Splits a Brep into pieces using Breps as cutters.</li>
<li>(since) 6.13</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="brep-splitienumerablecurve-cuttersdouble-intersectiontolerance">Brep[] Split(IEnumerable<!-- raw HTML omitted --> cutters,double intersectionTolerance)</h4>
<ul>
<li>(summary) Splits a Brep into pieces using curves, at least partially on the Brep, as cutters.</li>
<li>(since) 6.13</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="brep-splitienumerablegeometrybase-cuttersvector3d-normalbool-planviewdouble-intersectiontolerance">Brep[] Split(IEnumerable<!-- raw HTML omitted --> cutters,Vector3d normal,bool planView,double intersectionTolerance)</h4>
<ul>
<li>(summary) Splits a Brep into pieces using a combination of curves, to be extruded, and Breps as cutters.</li>
<li>(since) 6.13</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="void-standardize">void Standardize()</h4>
<ul>
<li>(summary) Standardizes all trims, edges, and faces in the brep.
After standardizing, there may be unused curves and surfaces in the
brep.  Call Brep.Compact to remove these unused curves and surfaces.</li>
<li>(since) 5.0</li>
<li>(returns) void This is some return comment</li>
</ul>
<h4 id="bool-transformcomponentienumerablecomponentindex-componentstransform-xformdouble-tolerancedouble-timelimitbool-usemultiplethreads">bool TransformComponent(IEnumerable<!-- raw HTML omitted --> components,Transform xform,double tolerance,double timeLimit,bool useMultipleThreads)</h4>
<ul>
<li>(summary) Transform an array of Brep components, bend neighbors to match, and leave the rest fixed.</li>
<li>(since) 6.0</li>
<li>(returns) bool This is some return comment</li>
</ul>
<h4 id="brep-trimbrep-cutterdouble-intersectiontolerance">Brep[] Trim(Brep cutter,double intersectionTolerance)</h4>
<ul>
<li>(summary) Trims a brep with an oriented cutter. The parts of the brep that lie inside
(opposite the normal) of the cutter are retained while the parts to the
outside (in the direction of the normal) are discarded.  If the Cutter is
closed, then a connected component of the Brep that does not intersect the
cutter is kept if and only if it is contained in the inside of cutter.
That is the region bounded by cutter opposite from the normal of cutter,
If cutter is not closed all these components are kept.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="brep-trimplane-cutterdouble-intersectiontolerance">Brep[] Trim(Plane cutter,double intersectionTolerance)</h4>
<ul>
<li>(summary) Trims a Brep with an oriented cutter.  The parts of Brep that lie inside
(opposite the normal) of the cutter are retained while the parts to the
outside ( in the direction of the normal ) are discarded. A connected
component of Brep that does not intersect the cutter is kept if and only
if it is contained in the inside of Cutter.  That is the region bounded by
cutter opposite from the normal of cutter, or in the case of a Plane cutter
the halfspace opposite from the plane normal.</li>
<li>(since) 5.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>
<h4 id="brep-unjoinedgesienumerableint-edgestounjoin">Brep[] UnjoinEdges(IEnumerable<!-- raw HTML omitted --> edgesToUnjoin)</h4>
<ul>
<li>(summary) Unjoins, or separates, edges within the Brep. Note, seams in closed surfaces will not separate.</li>
<li>(since) 6.0</li>
<li>(returns) Brep[] This is some return comment</li>
</ul>

  </section>

  <section>
    
      
    
  </section>
</article>

      </div>

      <div id="side" class="pr-1 bg-white">
        <aside class="pr-3">
          
  
    <div id="toc" class="Box Box--blue mb-3">
      <b>Brep</b><nav id="TableOfContents">
  <ul>
    <li><a href="#constructors">Constructors</a>
      <ul>
        <li></li>
      </ul>
    </li>
    <li><a href="#properties">Properties</a>
      <ul>
        <li></li>
      </ul>
    </li>
    <li><a href="#methods">Methods</a>
      <ul>
        <li></li>
      </ul>
    </li>
  </ul>
</nav></div>
  

  
    <div>
      
    </div>
  

        </aside>
      </div>

      <div id="footer" class="pt-2 pb-3 bg-white text-center">
        

  <span class="text-small text-gray">
    

    Powered by the
    <a href="https://github.com/qqhann/hugo-primer" class="link-gray-dark">Hugo-Primer</a> theme for
    <a href="https://gohugo.io" class="link-gray-dark">Hugo</a>.
  </span>


      </div>
    </div>

    
    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    
    <script type="text/x-mathjax-config">MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] } });</script>
    
  </body>
</html>
